# Configuration File for CAMPAREE
# Default configuration is for the including Baby mouse genome.
setup:
    run_id: null
    seed: 100
    dispatcher_mode: lsf
resources:
    directory_path: /home/crisl/beers_project/BEERS2.0/CAMPAREE/resources
    species_model: Mus_musculus.GRCm38
    reference_genome_filename: Mus_musculus.GRCm38.dna.oneline_seqs.fa
    chr_ploidy_filename: Mus_musculus.GRCm38.chr_ploidy.txt
    annotation_filename: Mus_musculus.GRCm38.93.annotation.txt
input:
    directory_path: /project/itmatlab/for_cris/Test_Mouse_Samples/data/expression/GRCm38/
    data: {'9576': {fastq_files: [9576_forward.fq.gz, 9576_reverse.fq.gz], gender: male}, '9577': {fastq_files: [9577_forward.fq.gz, 9577_reverse.fq.gz], gender: male}}

    {'ILB1': {fastq_files: [FGC1130_Illumina_ILB_9577_s_6_1_GCCAAT.fastq.gz, FGC1130_Illumina_ILB_9577_s_6_2_GCCAAT.fastq.gz], gender: male}, 'ILB2': {fastq_files: [FGC1130_Illumina_ILB_9578_s_6_1_CAGATC.fastq.gz, FGC1130_Illumina_ILB_9578_s_6_2_CAGATC.fastq.gz], gender: male}, 'ILB3': {fastq_files: [FGC1130_Illumina_ILB_9583_s_6_1_ATGTCA.fastq.gz, FGC1130_Illumina_ILB_9583_s_6_2_ATGTCA.fastq.gz], gender: male}, 'UNT1': {fastq_files: [FGC1130_Illumina_UNT_9576_s_6_1_ACAGTG.fastq.gz, FGC1130_Illumina_UNT_9576_s_6_2_ACAGTG.fastq.gz], gender: male}, 'UNT2': {fastq_files: [FGC1130_Illumina_UNT_9580_s_6_1_AGTCAA.fastq.gz, FGC1130_Illumina_UNT_9580_s_6_2_AGTCAA.fastq.gz], gender: male}, 'UNT3': {fastq_files: [FGC1130_Illumina_UNT_9584_s_6_1_CCGTCC.fastq.gz, FGC1130_Illumina_UNT_9584_s_6_2_CCGTCC.fastq.gz], gender: male}}
output:
    directory_path: /home/crisl/beers_project/BEERS2.0/data/
    type: molecule_file
    molecule_count: 50000
steps:
    - {step_name: genome_alignment.GenomeAlignmentStep, parameters: {'--runThreadN': 4, '--outFilterMismatchNmax': 33, '--seedSearchStartLmax': 33, '--alignSJoverhangMin': 8, '--readFilesCommand': zcat, '--outSAMstrandField': intronMotif, '--limitOutSJcollapsed': 1000000, '--limitSjdbInsertNsj': 1000000, '--outFilterMultimapNmax': 10, '--outFilterMismatchNoverLmax': 0.3, '--alignEndsType': Local}}
    - {step_name: genome_alignment.GenomeBamIndexStep}
    - {step_name: variants_finder.VariantsFinderStep, parameters: {sort_by_entropy: false, min_threshold: 0.03}}
    - {step_name: variants_compilation.VariantsCompilationStep}
    - {step_name: beagle.BeagleStep}
    - {step_name: genome_builder.GenomeBuilderStep, parameters: {ignore_indels: false, ignore_snps: false}}
    - {step_name: update_annotation_for_genome.UpdateAnnotationForGenomeStep}
    - {step_name: intron_quant.IntronQuantificationStep, parameters: {forward_read_is_sense: false, flank_size: 1500}}
    - {step_name: transcriptomes.TranscriptQuantificatAndMoleculeGenerationStep, parameters: {num_bowtie_threads: 7}}
